# .readthedocs.yaml  
version: 2  
  
build:  
  os: ubuntu-24.04  
  tools:  
    python: "3.10"  
    ruby: "3.3"  
  
  commands:  
    - echo "--- Initial working directory ---"
    - pwd
    - python website/scripts/sync_docs.py  
    - echo "--- After sync_docs.py, about to enter website directory ---"  
    # Use a multi-line block to ensure commands run within 'website'  
    - |  
      set -e # Exit immediately if a command exits with a non-zero status.  
      echo "--- Changing directory to website ---"  
      cd website  
      echo "--- Current directory (should be .../website) $(pwd) ---"  
      echo "--- Listing contents of website directory ---"  
      ls -la  
      echo "--- Installing bundler ---"  
      gem install bundler  
      echo "--- Running bundle install ---"  
      bundle install  
      echo "--- Building Jekyll site ---"  
      bundle exec jekyll build --config _config.yml,_config_rtd.yml --destination ../_readthedocs/html  
      echo "--- Jekyll build complete ---"  
